INSERT INTO USUARIO (ID, LOGIN, NOME, SENHA, DATA_CRIACAO, USUARIO_CRIACAO) VALUES (1, 'teste1', 'teste1', '123', '2017-04-27', 'ADMIN');
INSERT INTO USUARIO (ID, LOGIN, NOME, SENHA, DATA_CRIACAO, USUARIO_CRIACAO) VALUES (2, 'teste2', 'teste2', '123', '2017-04-27', 'ADMIN');
INSERT INTO USUARIO (ID, LOGIN, NOME, SENHA, DATA_CRIACAO, USUARIO_CRIACAO) VALUES (3, 'teste3', 'teste3', '123', '2017-04-27', 'ADMIN');

INSERT INTO PAPEL (ID, NOME) VALUES (1, 'ROLE_USER');
INSERT INTO PAPEL (ID, NOME) VALUES (2, 'ROLE_ADMIN');
INSERT INTO PAPEL (ID, NOME) VALUES (3, 'ROLE_GUEST');

INSERT INTO USUARIO_PAPEL (USUARIO_ID, PAPEL_ID) VALUES (1, 1);
INSERT INTO USUARIO_PAPEL (USUARIO_ID, PAPEL_ID) VALUES (2, 1);
INSERT INTO USUARIO_PAPEL (USUARIO_ID, PAPEL_ID) VALUES (3, 1);
INSERT INTO USUARIO_PAPEL (USUARIO_ID, PAPEL_ID) VALUES (1, 2);